### ISSUE TITLE
I would like to ask for help

### ISSUE THREAD

**Issue by kicq** [rt-2/RageMP-SAARPV-voiceChat#14]
could you help me? I want to install your voice chat on my Rage server version 1.41. And I installed it, but nothing happened, but it showed in the console
 "Initializing voiceChat script;
Started PeerJS server at 9000 port.
Completed voiceChat initializing;
Started HTTP server at 22006 port. "I installed the html folder on localhost, installed peer, registered the path to SSL.
I connected client and server scripts. Could you tell me what I did wrong? Or maybe this version of Rage does not support?

**Comment by rt-2** [comment]
You can't have SSL on localhost, that's not gonna work because the ingame browser is Chrome and he's the one who need to validate your SSL
